#navi package name   |  allow adjust navi volume  |  volume mix(0-100), default value: appset
#some cld navi(like cld.navi.*) is supported even it not config here
com.navitel                                 true    appset
title.navi                                  true    appset
com.mapabc.android.activity                 true    appset
cld.navi.*                                  true    appset
com.nuro.r1.main                            true    appset
com.autonavi.xm.navigation                  true    appset
com.autonavi.xmgd.navigator                 true    appset
com.autonavi.cmccmap                        true    appset
com.autonavi.minimap                        true    appset
com.autonavi.amapauto                       true    appset
com.autonavi.amapautolite                   true    appset
com.autonavi.*                              true    appset
com.mxnavi.mxnavi                           true    appset
com.baidu.BaiduMap                          true    appset
com.baidu.navi                              true    appset
com.baidu.BaiduMap.auto                     true    appset
com.sogou.map.android.maps                  true    appset
com.navngo.igo.javaclient                    true    appset
com.basarsoft.igo.javaclient                 true    appset
com.nng.igoprimoisr2013march24.javaclient    true    appset
com.nng.igo.primong.igoworld                 true    appset
com.nng.igoprimo.javaclient                  true    appset
com.nng.igoprimoisrael.javaclient            true    appset
ru.yandex.yandexnavi                         true    appset
com.sygic.aura_pndindash                     true    appset
com.mireo.dontpanic.mmi_pnd                 true    appset
com.sogou.map.android.maps                  true    appset
com.uu.uunavi                               true    appset
com.tigerknows                              true    appset
com.sogou.map.android.maps                  true    appset
com.mapquest.android.ace                    true    appset
cz.aponia.bor3                               true    appset
com.kingwaytek                              false   appset
com.kingwaytek.naviking3d                   false   appset
com.kingwaytek.naviking4g                   false   appset
com.kingwaytek.a5i_3d.plus                  false   appset
com.waze                                     true    appset
com.google.android.apps.maps                 true    appset
cld.navi.p3597.mainframe                    true    appset
com.tencent.navsns                          true    appset
com.tencent.map                             true    appset
com.movon.fcw                               true    appset
com.mapbar.android.carnavi                  true    appset
com.tencent.wecarnavi                       true    appset
cld.navi.k3618.mainframe                    true    appset
net.probki.cityguide.twmaps                 true    appset
com.here.app.maps                            true    appset
com.papago.s1OBU                            true    appset
com.skt.tmap.ku                             true    appset
com.locnall.KimGiSa                         true    appset
pl.aqurat.automapa                           true    appset
com.sygic.aura                               true    appset
com.tomtom.gplay.navapp                      true    appset
com.tomtom.gplay.navapp.nds                  true    appset
com.generalmagic.magicearth                  true    appset
net.osmand                                   true    appset
net.osmand.plus                              true    appset
ru.dublgis.dgismobile                        true    appset
com.mapfactor.navigator                      true    appset
ru.yandex.yandexmaps                         true    appset
com.mapswithme.maps.pro                      true    appset
app.organicmaps                              true    appset
